-- reviews.sql: Cria a tabela de reviews
CREATE TABLE IF NOT EXISTS review (
    review_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    review_text TEXT NOT NULL,
    review_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    inv_id INT NOT NULL,
    account_id INT NOT NULL,
    
    CONSTRAINT review_pk PRIMARY KEY (review_id),
    
    -- Chave Estrangeira para Inventory
    CONSTRAINT fk_inventory
        FOREIGN KEY (inv_id)
        REFERENCES inventory (inv_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    -- Chave Estrangeira para Account
    CONSTRAINT fk_account
        FOREIGN KEY (account_id)
        REFERENCES account (account_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);